server {
    listen 80;
    server_name localhost;
    # Wymuszenie przekierowania na HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    # Ścieżki do certyfikatów wewnątrz kontenera
    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    # Parametry SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://prestashop:80; # Przekazanie do kontenera PrestaShop
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # Kluczowe dla PrestaShop, aby wiedział, że jest za SSL
        proxy_set_header X-Forwarded-Proto https; 
    }
}