<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container09mtz1j\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container09mtz1j/appProdProjectContainer.php') {
    touch(__DIR__.'/Container09mtz1j.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container09mtz1j\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container09mtz1j\appProdProjectContainer([
    'container.build_hash' => '09mtz1j',
    'container.build_id' => '8c2c7b98',
    'container.build_time' => 1763814825,
], __DIR__.\DIRECTORY_SEPARATOR.'Container09mtz1j');
