parent: classic
name: classic-child
display_name: Dzik Style Theme
version: 1.0.0
assets:
  use_parent_assets: true
  css:
    all:
      - assets/css/custom.css
      - assets/css/footer.css
      - assets/css/header.css
      - assets/css/main.css
    product:
      - assets/css/product_page.css
    category:
      - assets/css/product-list.css
    page-registration:
      - assets/css/registration.css